export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/intro.html", { loader: () => import(/* webpackChunkName: "intro.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/intro.html.js"), meta: {"cover":"/assets/images/cover3.jpg","excerpt":"\n<p>将你的个人介绍和档案放置在此处。</p>\n","readingTime":{"minutes":0.08,"words":23},"title":"介绍页","icon":"circle-info","type":"article"} }],
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/index.html.js"), meta: {"title":"Home","icon":"house"} }],
  ["/website.html", { loader: () => import(/* webpackChunkName: "website.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/website.html.js"), meta: {"category":["导航"],"tag":["页面配置","使用指南"],"sticky":true,"cover":"https://cdn.jsdelivr.net/gh/Cunyanger/pic_bed@master/rain_sta.png","excerpt":"<h2>工具类</h2>\n<table>\n<thead>\n<tr>\n<th></th>\n<th></th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><a href=\"https://fontawesome.com.cn/v5\" target=\"_blank\" rel=\"noopener noreferrer\">图标库 v5 - FontAwesome 字体图标中文 Icon</a></td>\n<td></td>\n</tr>\n<tr>\n<td></td>\n<td></td>\n</tr>\n</tbody>\n</table>\n","readingTime":{"minutes":0.36,"words":108},"title":"网页导航","icon":"globe","order":3,"type":"article"} }],
  ["/cyber/page.html", { loader: () => import(/* webpackChunkName: "cyber_page.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/cyber/page.html.js"), meta: {"category":["使用指南"],"tag":["博客","图床"],"sticky":true,"cover":"/assets/images/cover1.jpg","excerpt":"<p>github作为云存储，jsDeliv作为CDN，PicGo充作为图片git push工具</p>\n","readingTime":{"minutes":0.95,"words":286},"title":"Github+PicGo搭建图床","icon":"file","order":0,"type":"article"} }],
  ["/cyber/", { loader: () => import(/* webpackChunkName: "cyber_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/cyber/index.html.js"), meta: {"category":["使用指南"],"readingTime":{"minutes":0.06,"words":17},"title":"赛博小记","icon":"laptop-code","type":"article"} }],
  ["/demo/disable.html", { loader: () => import(/* webpackChunkName: "demo_disable.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/demo/disable.html.js"), meta: {"category":["使用指南"],"tag":["禁用"],"excerpt":"<p>你可以通过设置页面的 Frontmatter，在页面禁用功能与布局。</p>\n","readingTime":{"minutes":0.43,"words":128},"title":"布局与功能禁用","icon":"gears","order":4,"type":"article"} }],
  ["/demo/encrypt.html", { loader: () => import(/* webpackChunkName: "demo_encrypt.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/demo/encrypt.html.js"), meta: {"category":["使用指南"],"tag":["加密"],"isEncrypted":true,"readingTime":{"minutes":0.51,"words":154},"title":"密码加密的文章","icon":"lock","type":"article"} }],
  ["/demo/layout.html", { loader: () => import(/* webpackChunkName: "demo_layout.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/demo/layout.html.js"), meta: {"category":["指南"],"tag":["布局"],"excerpt":"<p>布局包括:</p>\n<ul>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/navbar.html\" target=\"_blank\" rel=\"noopener noreferrer\">导航栏</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/sidebar.html\" target=\"_blank\" rel=\"noopener noreferrer\">侧边栏</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/footer.html\" target=\"_blank\" rel=\"noopener noreferrer\">页脚</a></li>\n</ul>","readingTime":{"minutes":0.53,"words":159},"title":"布局","icon":"object-group","order":2,"type":"article"} }],
  ["/demo/markdown.html", { loader: () => import(/* webpackChunkName: "demo_markdown.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/demo/markdown.html.js"), meta: {"category":["使用指南"],"tag":["Markdown"],"excerpt":"<p>VuePress 主要从 Markdown 文件生成页面。因此，你可以使用它轻松生成文档或博客站点。</p>\n<p>你需要创建并编写 Markdown，以便 VuePress 可以根据文件结构将它们转换为不同的页面。</p>\n","readingTime":{"minutes":3.47,"words":1041},"title":"Markdown 展示","icon":"fa6-brands:markdown","order":2,"type":"article"} }],
  ["/demo/page.html", { loader: () => import(/* webpackChunkName: "demo_page.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/demo/page.html.js"), meta: {"author":"Ms.Hope","date":1577836800000,"localizedDate":"2020年1月1日","category":["使用指南"],"tag":["页面配置","使用指南"],"sticky":true,"cover":"/assets/images/cover1.jpg","excerpt":"<p><code>more</code> 注释之前的内容被视为文章摘要。</p>\n","readingTime":{"minutes":1.76,"words":529},"title":"页面配置","icon":"file","order":3,"type":"article"} }],
  ["/demo/", { loader: () => import(/* webpackChunkName: "demo_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/demo/index.html.js"), meta: {"category":["使用指南"],"readingTime":{"minutes":0.07,"words":22},"title":"主要功能与配置演示","icon":"laptop-code","type":"article"} }],
  ["/notes/literature/1.html", { loader: () => import(/* webpackChunkName: "notes_literature_1.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/notes/literature/1.html.js"), meta: {"date":1640995200000,"localizedDate":"2022年1月1日","category":["苹果"],"tag":["红","大","圆"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.11,"words":34},"title":"苹果 1","icon":"pen-to-square","type":"article"} }],
  ["/notes/literature/2.html", { loader: () => import(/* webpackChunkName: "notes_literature_2.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/notes/literature/2.html.js"), meta: {"date":1641081600000,"localizedDate":"2022年1月2日","category":["苹果"],"tag":["红","大","圆"],"excerpt":"\n<p>一个被星标了的苹果文章。</p>\n","readingTime":{"minutes":0.16,"words":48},"title":"苹果 2","icon":"pen-to-square","type":"article"} }],
  ["/notes/social_sciences/1.html", { loader: () => import(/* webpackChunkName: "notes_social_sciences_1.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/notes/social_sciences/1.html.js"), meta: {"date":1640995200000,"localizedDate":"2022年1月1日","category":["苹果"],"tag":["红","大","圆"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.11,"words":34},"title":"苹果 1","icon":"pen-to-square","type":"article"} }],
  ["/notes/social_sciences/2.html", { loader: () => import(/* webpackChunkName: "notes_social_sciences_2.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/notes/social_sciences/2.html.js"), meta: {"date":1641081600000,"localizedDate":"2022年1月2日","category":["苹果"],"tag":["红","大","圆"],"excerpt":"\n<p>一个被星标了的苹果文章。</p>\n","readingTime":{"minutes":0.16,"words":48},"title":"苹果 2","icon":"pen-to-square","type":"article"} }],
  ["/notes/software/2.html", { loader: () => import(/* webpackChunkName: "notes_software_2.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/notes/software/2.html.js"), meta: {"date":1641081600000,"localizedDate":"2022年1月2日","category":["苹果"],"tag":["红","大","圆"],"excerpt":"\n<p>一个被星标了的苹果文章。</p>\n","readingTime":{"minutes":0.16,"words":48},"title":"苹果 2","icon":"pen-to-square","type":"article"} }],
  ["/notes/software/4.html", { loader: () => import(/* webpackChunkName: "notes_software_4.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/notes/software/4.html.js"), meta: {"date":1641254400000,"localizedDate":"2022年1月4日","category":["苹果","水果"],"tag":["红","大","圆"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.12,"words":36},"title":"苹果 4","icon":"pen-to-square","type":"article"} }],
  ["/notes/software/The%20Mythical%20Man-Month.html", { loader: () => import(/* webpackChunkName: "notes_software_The Mythical Man-Month.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/notes/software/The Mythical Man-Month.html.js"), meta: {"date":1640995200000,"localizedDate":"2022年1月1日","category":["苹果"],"tag":["红","大","圆"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.12,"words":35},"title":"人月神话","icon":"pen-to-square","type":"article"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
  ["/notes/literature/", { loader: () => import(/* webpackChunkName: "notes_literature_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/notes/literature/index.html.js"), meta: {"title":"Literature"} }],
  ["/notes/", { loader: () => import(/* webpackChunkName: "notes_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/notes/index.html.js"), meta: {"title":"Notes"} }],
  ["/notes/social_sciences/", { loader: () => import(/* webpackChunkName: "notes_social_sciences_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/notes/social_sciences/index.html.js"), meta: {"title":"Social Sciences"} }],
  ["/notes/software/", { loader: () => import(/* webpackChunkName: "notes_software_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/notes/software/index.html.js"), meta: {"title":"Software"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/category/index.html.js"), meta: {"title":"分类","index":false} }],
  ["/category/%E5%AF%BC%E8%88%AA/", { loader: () => import(/* webpackChunkName: "category_导航_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/category/导航/index.html.js"), meta: {"title":"导航 分类","index":false} }],
  ["/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "category_使用指南_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/category/使用指南/index.html.js"), meta: {"title":"使用指南 分类","index":false} }],
  ["/category/%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "category_指南_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/category/指南/index.html.js"), meta: {"title":"指南 分类","index":false} }],
  ["/category/%E8%8B%B9%E6%9E%9C/", { loader: () => import(/* webpackChunkName: "category_苹果_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/category/苹果/index.html.js"), meta: {"title":"苹果 分类","index":false} }],
  ["/category/%E6%B0%B4%E6%9E%9C/", { loader: () => import(/* webpackChunkName: "category_水果_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/category/水果/index.html.js"), meta: {"title":"水果 分类","index":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/tag/index.html.js"), meta: {"title":"标签","index":false} }],
  ["/tag/%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE/", { loader: () => import(/* webpackChunkName: "tag_页面配置_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/tag/页面配置/index.html.js"), meta: {"title":"标签: 页面配置","index":false} }],
  ["/tag/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "tag_使用指南_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/tag/使用指南/index.html.js"), meta: {"title":"标签: 使用指南","index":false} }],
  ["/tag/%E5%8D%9A%E5%AE%A2/", { loader: () => import(/* webpackChunkName: "tag_博客_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/tag/博客/index.html.js"), meta: {"title":"标签: 博客","index":false} }],
  ["/tag/%E5%9B%BE%E5%BA%8A/", { loader: () => import(/* webpackChunkName: "tag_图床_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/tag/图床/index.html.js"), meta: {"title":"标签: 图床","index":false} }],
  ["/tag/%E7%A6%81%E7%94%A8/", { loader: () => import(/* webpackChunkName: "tag_禁用_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/tag/禁用/index.html.js"), meta: {"title":"标签: 禁用","index":false} }],
  ["/tag/%E5%8A%A0%E5%AF%86/", { loader: () => import(/* webpackChunkName: "tag_加密_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/tag/加密/index.html.js"), meta: {"title":"标签: 加密","index":false} }],
  ["/tag/%E5%B8%83%E5%B1%80/", { loader: () => import(/* webpackChunkName: "tag_布局_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/tag/布局/index.html.js"), meta: {"title":"标签: 布局","index":false} }],
  ["/tag/markdown/", { loader: () => import(/* webpackChunkName: "tag_markdown_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/tag/markdown/index.html.js"), meta: {"title":"标签: Markdown","index":false} }],
  ["/tag/%E7%BA%A2/", { loader: () => import(/* webpackChunkName: "tag_红_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/tag/红/index.html.js"), meta: {"title":"标签: 红","index":false} }],
  ["/tag/%E5%A4%A7/", { loader: () => import(/* webpackChunkName: "tag_大_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/tag/大/index.html.js"), meta: {"title":"标签: 大","index":false} }],
  ["/tag/%E5%9C%86/", { loader: () => import(/* webpackChunkName: "tag_圆_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/tag/圆/index.html.js"), meta: {"title":"标签: 圆","index":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/article/index.html.js"), meta: {"title":"文章","index":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/star/index.html.js"), meta: {"title":"星标","index":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"D:/WorkSpace/MySpace/blog_theme/src/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"title":"时间轴","index":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
